FROM althack/ros2:jazzy-dev

# ** [Optional] Uncomment this section to install additional packages. **
#
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
   && apt-get -y install --no-install-recommends ros-jazzy-ros-gz \
   #
   # Clean up
   && apt-get autoremove -y \
   && apt-get clean -y \
   && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=dialog

# Set the env variable to allow rosdep installation of pip packages
ENV PIP_BREAK_SYSTEM_PACKAGES=1

# Set up auto-source of workspace for ros user
ARG WORKSPACE
RUN echo "if [ -f ${WORKSPACE}/install/local_setup.bash ]; then source ${WORKSPACE}/install/local_setup.bash; fi" >> /home/ros/.bashrc
